cors:
  allowed:
    origin: ${CORS_ALLOWED_ORIGIN}

spring:
  profiles:
    group:
      local: local
      dev: dev
      prod: prod
  config:
    import:
      - classpath: application-jwt.yml
      - classpath: application-dbsource.yml
