fcm:
  file_path: ${FCM_JSON_PATH}
  url: https:/fcm.googleapis.com/v1/projects/${FCM_PROJECT_ID}/messages:send
  google_api: https://www.googleapis.com/auth/cloud-platform
  project_id: ${FCM_PROJECT_ID}
