
spring:
  config:
    activate:
      on-profile: prod

ai:
  base-url: ${PROD_AI_BASE_URL}
  timeout-seconds: ${PROD_AI_TIMEOUT_SECONDS}


---

spring:
  config:
    activate:
      on-profile: dev

ai:
  base-url: ${DEV_AI_BASE_URL}
  timeout-seconds: ${DEV_AI_TIMEOUT_SECONDS}

---

spring:
  config:
    activate:
      on-profile: local

ai:
  base-url: ${LOCAL_AI_BASE_URL}
  timeout-seconds: ${LOCAL_AI_TIMEOUT_SECONDS}
